"""empty message

Revision ID: a5a5f5663072
Revises: 95c413f725cd
Create Date: 2023-12-16 21:59:09.581833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a5f5663072'
down_revision = '95c413f725cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=False)
        batch_op.alter_column('key_ingredients',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=False)
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=False)
        batch_op.alter_column('skin_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('skin_type',
               existing_type=sa.Text(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('profile_image',
               existing_type=sa.Text(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.Text(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('key_ingredients',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
