"""create tables

Revision ID: cb9ba7a4a4c7
Revises: 
Create Date: 2024-03-24 15:00:30.661062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9ba7a4a4c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=False),
    sa.Column('skin_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='skinnotrx_schema'
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['skinnotrx_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='skinnotrx_schema'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=60), nullable=False),
    sa.Column('product_name', sa.String(length=60), nullable=False),
    sa.Column('product_type', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('key_ingredients', sa.String(length=500), nullable=True),
    sa.Column('product_link', sa.String(length=500), nullable=True),
    sa.Column('preview_image', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['skinnotrx_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name'),
    schema='skinnotrx_schema'
    )
    op.create_table('favorite_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['skinnotrx_schema.collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['skinnotrx_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='skinnotrx_schema'
    )
    op.create_table('favorite_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['skinnotrx_schema.products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['skinnotrx_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='skinnotrx_schema'
    )
    op.create_table('product_collections',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['skinnotrx_schema.collections.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['skinnotrx_schema.products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'collection_id'),
    schema='skinnotrx_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_collections', schema='skinnotrx_schema')
    op.drop_table('favorite_products', schema='skinnotrx_schema')
    op.drop_table('favorite_collections', schema='skinnotrx_schema')
    op.drop_table('products', schema='skinnotrx_schema')
    op.drop_table('collections', schema='skinnotrx_schema')
    op.drop_table('users', schema='skinnotrx_schema')
    # ### end Alembic commands ###
